#pragma once

/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1210) handshake_HandshakeRequest_epk_sender_pqc_t;
typedef PB_BYTES_ARRAY_T(46) handshake_HandshakeRequest_epk_sender_ec_t;
typedef PB_BYTES_ARRAY_T(1088) handshake_HandshakeRequest_cipher_init_rekey_t;
typedef PB_BYTES_ARRAY_T(10240) handshake_HandshakeRequest_ocspresp_mcs_t;
typedef struct _handshake_HandshakeRequest {
    handshake_HandshakeRequest_epk_sender_pqc_t epk_sender_pqc;
    handshake_HandshakeRequest_epk_sender_ec_t epk_sender_ec;
    handshake_HandshakeRequest_cipher_init_rekey_t cipher_init_rekey;
    handshake_HandshakeRequest_ocspresp_mcs_t ocspresp_mcs;
    uint32_t sdls_key_id;
} handshake_HandshakeRequest;

typedef PB_BYTES_ARRAY_T(1088) handshake_HandshakeResponse_cipher_rekey_resp1_t;
typedef PB_BYTES_ARRAY_T(1088) handshake_HandshakeResponse_cipher_rekey_resp2_t;
typedef PB_BYTES_ARRAY_T(46) handshake_HandshakeResponse_epk_replier_ec_t;
typedef PB_BYTES_ARRAY_T(48) handshake_HandshakeResponse_tag_replier_t;
typedef struct _handshake_HandshakeResponse {
    handshake_HandshakeResponse_cipher_rekey_resp1_t cipher_rekey_resp1;
    handshake_HandshakeResponse_cipher_rekey_resp2_t cipher_rekey_resp2;
    handshake_HandshakeResponse_epk_replier_ec_t epk_replier_ec;
    handshake_HandshakeResponse_tag_replier_t tag_replier;
} handshake_HandshakeResponse;

typedef PB_BYTES_ARRAY_T(48) handshake_HandshakeKeyConfirmation_tag_sender_t;
typedef struct _handshake_HandshakeKeyConfirmation {
    handshake_HandshakeKeyConfirmation_tag_sender_t tag_sender;
} handshake_HandshakeKeyConfirmation;

typedef struct _handshake_HandshakeMessage {
    pb_size_t which_payload;
    union _handshake_HandshakeMessage_payload {
        handshake_HandshakeRequest request;
        handshake_HandshakeResponse response;
        handshake_HandshakeKeyConfirmation keyconfirmation;
    } payload;
} handshake_HandshakeMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define handshake_HandshakeRequest_init_default  {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0}
#define handshake_HandshakeResponse_init_default {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}
#define handshake_HandshakeKeyConfirmation_init_default {{0, {0}}}
#define handshake_HandshakeMessage_init_default  {0, {handshake_HandshakeRequest_init_default}}
#define handshake_HandshakeRequest_init_zero     {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0}
#define handshake_HandshakeResponse_init_zero    {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}
#define handshake_HandshakeKeyConfirmation_init_zero {{0, {0}}}
#define handshake_HandshakeMessage_init_zero     {0, {handshake_HandshakeRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define handshake_HandshakeRequest_epk_sender_pqc_tag 1
#define handshake_HandshakeRequest_epk_sender_ec_tag 2
#define handshake_HandshakeRequest_cipher_init_rekey_tag 3
#define handshake_HandshakeRequest_ocspresp_mcs_tag 4
#define handshake_HandshakeRequest_sdls_key_id_tag 5
#define handshake_HandshakeResponse_cipher_rekey_resp1_tag 1
#define handshake_HandshakeResponse_cipher_rekey_resp2_tag 2
#define handshake_HandshakeResponse_epk_replier_ec_tag 3
#define handshake_HandshakeResponse_tag_replier_tag 4
#define handshake_HandshakeKeyConfirmation_tag_sender_tag 1
#define handshake_HandshakeMessage_request_tag   1
#define handshake_HandshakeMessage_response_tag  2
#define handshake_HandshakeMessage_keyconfirmation_tag 3

/* Struct field encoding specification for nanopb */
#define handshake_HandshakeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    epk_sender_pqc,    1) \
X(a, STATIC,   SINGULAR, BYTES,    epk_sender_ec,     2) \
X(a, STATIC,   SINGULAR, BYTES,    cipher_init_rekey,   3) \
X(a, STATIC,   SINGULAR, BYTES,    ocspresp_mcs,      4) \
X(a, STATIC,   SINGULAR, UINT32,   sdls_key_id,       5)
#define handshake_HandshakeRequest_CALLBACK NULL
#define handshake_HandshakeRequest_DEFAULT NULL

#define handshake_HandshakeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    cipher_rekey_resp1,   1) \
X(a, STATIC,   SINGULAR, BYTES,    cipher_rekey_resp2,   2) \
X(a, STATIC,   SINGULAR, BYTES,    epk_replier_ec,    3) \
X(a, STATIC,   SINGULAR, BYTES,    tag_replier,       4)
#define handshake_HandshakeResponse_CALLBACK NULL
#define handshake_HandshakeResponse_DEFAULT NULL

#define handshake_HandshakeKeyConfirmation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    tag_sender,        1)
#define handshake_HandshakeKeyConfirmation_CALLBACK NULL
#define handshake_HandshakeKeyConfirmation_DEFAULT NULL

#define handshake_HandshakeMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,request,payload.request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,response,payload.response),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,keyconfirmation,payload.keyconfirmation),   3)
#define handshake_HandshakeMessage_CALLBACK NULL
#define handshake_HandshakeMessage_DEFAULT NULL
#define handshake_HandshakeMessage_payload_request_MSGTYPE handshake_HandshakeRequest
#define handshake_HandshakeMessage_payload_response_MSGTYPE handshake_HandshakeResponse
#define handshake_HandshakeMessage_payload_keyconfirmation_MSGTYPE handshake_HandshakeKeyConfirmation

extern const pb_msgdesc_t handshake_HandshakeRequest_msg;
extern const pb_msgdesc_t handshake_HandshakeResponse_msg;
extern const pb_msgdesc_t handshake_HandshakeKeyConfirmation_msg;
extern const pb_msgdesc_t handshake_HandshakeMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define handshake_HandshakeRequest_fields &handshake_HandshakeRequest_msg
#define handshake_HandshakeResponse_fields &handshake_HandshakeResponse_msg
#define handshake_HandshakeKeyConfirmation_fields &handshake_HandshakeKeyConfirmation_msg
#define handshake_HandshakeMessage_fields &handshake_HandshakeMessage_msg

/* Maximum encoded size of messages (where known) */
#define HANDSHAKE_PROTOBUF_HANDSHAKE_PB_H_MAX_SIZE handshake_HandshakeMessage_size
#define handshake_HandshakeKeyConfirmation_size  50
#define handshake_HandshakeMessage_size          12604
#define handshake_HandshakeRequest_size          12601
#define handshake_HandshakeResponse_size         2280

#ifdef __cplusplus
} /* extern "C" */
#endif
