/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "handshake.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(handshake_HandshakeRequest, handshake_HandshakeRequest, 4)


PB_BIND(handshake_HandshakeResponse, handshake_HandshakeResponse, 2)


PB_BIND(handshake_HandshakeKeyConfirmation, handshake_HandshakeKeyConfirmation, AUTO)


PB_BIND(handshake_HandshakeMessage, handshake_HandshakeMessage, 4)



