/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PKI_PKI_PB_H_INCLUDED
#define PB_PKI_PKI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(10240) pki_InitTrust_cert_ca_t;
typedef PB_BYTES_ARRAY_T(128) pki_InitTrust_pss_sat_t;
/* Ground -> flight: install the CA certificate and the pre-shared secret.
 Must be uplinked over the authenticated channel (ground responsibility). */
typedef struct _pki_InitTrust {
    pki_InitTrust_cert_ca_t cert_ca; /* X.509 certificate, DER */
    pki_InitTrust_pss_sat_t pss_sat; /* raw pre-shared secret, >= 32 bytes */
} pki_InitTrust;

/* Ground -> flight: trigger onboard keygen + CSR generation. */
typedef struct _pki_RenewCertCommand {
    uint32_t nonce;
} pki_RenewCertCommand;

typedef PB_BYTES_ARRAY_T(2400) pki_CsrRequest_csr_t;
typedef PB_BYTES_ARRAY_T(48) pki_CsrRequest_mac_t;
/* Flight -> ground: csr is a DER CertificationRequestInfo (RFC 2986 TBS,
 unsigned - ML-KEM keys cannot sign); mac is HMAC-SHA3-384(PSS_sat, csr). */
typedef struct _pki_CsrRequest {
    pki_CsrRequest_csr_t csr;
    pki_CsrRequest_mac_t mac;
} pki_CsrRequest;

typedef PB_BYTES_ARRAY_T(10240) pki_NewCertificate_cert_sat_t;
/* Ground -> flight: the CA-signed certificate answering a CsrRequest. */
typedef struct _pki_NewCertificate {
    pki_NewCertificate_cert_sat_t cert_sat; /* X.509 certificate, DER */
} pki_NewCertificate;

typedef PB_BYTES_ARRAY_T(10240) pki_CertExchange_cert_mcs_t;
typedef PB_BYTES_ARRAY_T(10240) pki_CertExchange_ocsp_resp_mcs_t;
/* Ground -> flight: MCS certificate with its stapled OCSP response. */
typedef struct _pki_CertExchange {
    pki_CertExchange_cert_mcs_t cert_mcs; /* X.509 certificate, DER */
    pki_CertExchange_ocsp_resp_mcs_t ocsp_resp_mcs; /* OCSP response (RFC 6960), DER */
} pki_CertExchange;

/* Ground -> flight: request the current SAT certificate. */
typedef struct _pki_CertSatRequest {
    uint32_t nonce;
} pki_CertSatRequest;

typedef PB_BYTES_ARRAY_T(10240) pki_CertSat_cert_sat_t;
/* Flight -> ground: the current SAT certificate. */
typedef struct _pki_CertSat {
    pki_CertSat_cert_sat_t cert_sat; /* X.509 certificate, DER */
} pki_CertSat;

/* Flight -> ground: ack/failure for a ground-initiated operation.
 op mirrors the PkiMessage payload tag this status responds to. */
typedef struct _pki_PkiStatus {
    uint32_t op;
    uint32_t code; /* 0 = success, otherwise error code */
    char detail[64];
} pki_PkiStatus;

typedef struct _pki_PkiMessage {
    pb_size_t which_payload;
    union {
        pki_InitTrust init_trust;
        pki_RenewCertCommand renew_cert;
        pki_CsrRequest csr_request;
        pki_NewCertificate new_certificate;
        pki_CertExchange cert_exchange;
        pki_CertSatRequest cert_sat_request;
        pki_CertSat cert_sat;
        pki_PkiStatus status;
    } payload;
} pki_PkiMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define pki_InitTrust_init_default               {{0, {0}}, {0, {0}}}
#define pki_RenewCertCommand_init_default        {0}
#define pki_CsrRequest_init_default              {{0, {0}}, {0, {0}}}
#define pki_NewCertificate_init_default          {{0, {0}}}
#define pki_CertExchange_init_default            {{0, {0}}, {0, {0}}}
#define pki_CertSatRequest_init_default          {0}
#define pki_CertSat_init_default                 {{0, {0}}}
#define pki_PkiStatus_init_default               {0, 0, ""}
#define pki_PkiMessage_init_default              {0, {pki_InitTrust_init_default}}
#define pki_InitTrust_init_zero                  {{0, {0}}, {0, {0}}}
#define pki_RenewCertCommand_init_zero           {0}
#define pki_CsrRequest_init_zero                 {{0, {0}}, {0, {0}}}
#define pki_NewCertificate_init_zero             {{0, {0}}}
#define pki_CertExchange_init_zero               {{0, {0}}, {0, {0}}}
#define pki_CertSatRequest_init_zero             {0}
#define pki_CertSat_init_zero                    {{0, {0}}}
#define pki_PkiStatus_init_zero                  {0, 0, ""}
#define pki_PkiMessage_init_zero                 {0, {pki_InitTrust_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define pki_InitTrust_cert_ca_tag                1
#define pki_InitTrust_pss_sat_tag                2
#define pki_RenewCertCommand_nonce_tag           1
#define pki_CsrRequest_csr_tag                   1
#define pki_CsrRequest_mac_tag                   2
#define pki_NewCertificate_cert_sat_tag          1
#define pki_CertExchange_cert_mcs_tag            1
#define pki_CertExchange_ocsp_resp_mcs_tag       2
#define pki_CertSatRequest_nonce_tag             1
#define pki_CertSat_cert_sat_tag                 1
#define pki_PkiStatus_op_tag                     1
#define pki_PkiStatus_code_tag                   2
#define pki_PkiStatus_detail_tag                 3
#define pki_PkiMessage_init_trust_tag            1
#define pki_PkiMessage_renew_cert_tag            2
#define pki_PkiMessage_csr_request_tag           3
#define pki_PkiMessage_new_certificate_tag       4
#define pki_PkiMessage_cert_exchange_tag         5
#define pki_PkiMessage_cert_sat_request_tag      6
#define pki_PkiMessage_cert_sat_tag              7
#define pki_PkiMessage_status_tag                8

/* Struct field encoding specification for nanopb */
#define pki_InitTrust_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    cert_ca,           1) \
X(a, STATIC,   SINGULAR, BYTES,    pss_sat,           2)
#define pki_InitTrust_CALLBACK NULL
#define pki_InitTrust_DEFAULT NULL

#define pki_RenewCertCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nonce,             1)
#define pki_RenewCertCommand_CALLBACK NULL
#define pki_RenewCertCommand_DEFAULT NULL

#define pki_CsrRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    csr,               1) \
X(a, STATIC,   SINGULAR, BYTES,    mac,               2)
#define pki_CsrRequest_CALLBACK NULL
#define pki_CsrRequest_DEFAULT NULL

#define pki_NewCertificate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    cert_sat,          1)
#define pki_NewCertificate_CALLBACK NULL
#define pki_NewCertificate_DEFAULT NULL

#define pki_CertExchange_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    cert_mcs,          1) \
X(a, STATIC,   SINGULAR, BYTES,    ocsp_resp_mcs,     2)
#define pki_CertExchange_CALLBACK NULL
#define pki_CertExchange_DEFAULT NULL

#define pki_CertSatRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nonce,             1)
#define pki_CertSatRequest_CALLBACK NULL
#define pki_CertSatRequest_DEFAULT NULL

#define pki_CertSat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    cert_sat,          1)
#define pki_CertSat_CALLBACK NULL
#define pki_CertSat_DEFAULT NULL

#define pki_PkiStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   op,                1) \
X(a, STATIC,   SINGULAR, UINT32,   code,              2) \
X(a, STATIC,   SINGULAR, STRING,   detail,            3)
#define pki_PkiStatus_CALLBACK NULL
#define pki_PkiStatus_DEFAULT NULL

#define pki_PkiMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,init_trust,payload.init_trust),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,renew_cert,payload.renew_cert),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,csr_request,payload.csr_request),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,new_certificate,payload.new_certificate),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cert_exchange,payload.cert_exchange),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cert_sat_request,payload.cert_sat_request),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cert_sat,payload.cert_sat),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   8)
#define pki_PkiMessage_CALLBACK NULL
#define pki_PkiMessage_DEFAULT NULL
#define pki_PkiMessage_payload_init_trust_MSGTYPE pki_InitTrust
#define pki_PkiMessage_payload_renew_cert_MSGTYPE pki_RenewCertCommand
#define pki_PkiMessage_payload_csr_request_MSGTYPE pki_CsrRequest
#define pki_PkiMessage_payload_new_certificate_MSGTYPE pki_NewCertificate
#define pki_PkiMessage_payload_cert_exchange_MSGTYPE pki_CertExchange
#define pki_PkiMessage_payload_cert_sat_request_MSGTYPE pki_CertSatRequest
#define pki_PkiMessage_payload_cert_sat_MSGTYPE pki_CertSat
#define pki_PkiMessage_payload_status_MSGTYPE pki_PkiStatus

extern const pb_msgdesc_t pki_InitTrust_msg;
extern const pb_msgdesc_t pki_RenewCertCommand_msg;
extern const pb_msgdesc_t pki_CsrRequest_msg;
extern const pb_msgdesc_t pki_NewCertificate_msg;
extern const pb_msgdesc_t pki_CertExchange_msg;
extern const pb_msgdesc_t pki_CertSatRequest_msg;
extern const pb_msgdesc_t pki_CertSat_msg;
extern const pb_msgdesc_t pki_PkiStatus_msg;
extern const pb_msgdesc_t pki_PkiMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pki_InitTrust_fields &pki_InitTrust_msg
#define pki_RenewCertCommand_fields &pki_RenewCertCommand_msg
#define pki_CsrRequest_fields &pki_CsrRequest_msg
#define pki_NewCertificate_fields &pki_NewCertificate_msg
#define pki_CertExchange_fields &pki_CertExchange_msg
#define pki_CertSatRequest_fields &pki_CertSatRequest_msg
#define pki_CertSat_fields &pki_CertSat_msg
#define pki_PkiStatus_fields &pki_PkiStatus_msg
#define pki_PkiMessage_fields &pki_PkiMessage_msg

/* Maximum encoded size of messages (where known) */
#define PKI_PKI_PB_H_MAX_SIZE                    pki_PkiMessage_size
#define pki_CertExchange_size                    20486
#define pki_CertSatRequest_size                  6
#define pki_CertSat_size                         10243
#define pki_CsrRequest_size                      2453
#define pki_InitTrust_size                       10374
#define pki_NewCertificate_size                  10243
#define pki_PkiMessage_size                      20490
#define pki_PkiStatus_size                       77
#define pki_RenewCertCommand_size                6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
