/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "pki.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pki_InitTrust, pki_InitTrust, 4)


PB_BIND(pki_RenewCertCommand, pki_RenewCertCommand, AUTO)


PB_BIND(pki_CsrRequest, pki_CsrRequest, 2)


PB_BIND(pki_NewCertificate, pki_NewCertificate, 4)


PB_BIND(pki_CertExchange, pki_CertExchange, 4)


PB_BIND(pki_CertSatRequest, pki_CertSatRequest, AUTO)


PB_BIND(pki_CertSat, pki_CertSat, 4)


PB_BIND(pki_PkiStatus, pki_PkiStatus, AUTO)


PB_BIND(pki_PkiMessage, pki_PkiMessage, 4)



